-- Tracer Bacaan Al-Qur'an PKG
-- Jalankan hanya bila deploy tidak memakai `php artisan migrate --force`.

CREATE TABLE IF NOT EXISTS `quran_reading_sheets` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `siswa_id` bigint unsigned NOT NULL,
  `public_id` char(36) NOT NULL,
  `token_hash` varchar(64) NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'active',
  `row_count` tinyint unsigned NOT NULL DEFAULT 12,
  `last_position` json DEFAULT NULL,
  `generated_by` bigint unsigned DEFAULT NULL,
  `revoked_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `quran_reading_sheets_public_id_unique` (`public_id`),
  KEY `quran_reading_sheets_status_index` (`status`),
  KEY `quran_reading_sheets_siswa_id_foreign` (`siswa_id`),
  KEY `quran_reading_sheets_generated_by_foreign` (`generated_by`),
  CONSTRAINT `quran_reading_sheets_siswa_id_foreign` FOREIGN KEY (`siswa_id`) REFERENCES `siswa` (`id`) ON DELETE CASCADE,
  CONSTRAINT `quran_reading_sheets_generated_by_foreign` FOREIGN KEY (`generated_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `quran_reading_scans` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `siswa_id` bigint unsigned NOT NULL,
  `sheet_id` bigint unsigned DEFAULT NULL,
  `uploaded_by_type` varchar(20) NOT NULL,
  `uploaded_by_id` bigint unsigned NOT NULL,
  `original_path` varchar(255) NOT NULL,
  `processed_path` varchar(255) DEFAULT NULL,
  `status` varchar(24) NOT NULL DEFAULT 'awaiting_confirmation',
  `extracted_rows` json DEFAULT NULL,
  `metadata` json DEFAULT NULL,
  `confirmed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `quran_reading_scans_siswa_id_foreign` (`siswa_id`),
  KEY `quran_reading_scans_sheet_id_foreign` (`sheet_id`),
  KEY `quran_reading_scans_status_index` (`status`),
  KEY `quran_reading_scans_uploaded_by_type_uploaded_by_id_index` (`uploaded_by_type`,`uploaded_by_id`),
  CONSTRAINT `quran_reading_scans_siswa_id_foreign` FOREIGN KEY (`siswa_id`) REFERENCES `siswa` (`id`) ON DELETE CASCADE,
  CONSTRAINT `quran_reading_scans_sheet_id_foreign` FOREIGN KEY (`sheet_id`) REFERENCES `quran_reading_sheets` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `quran_reading_entries` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `siswa_id` bigint unsigned NOT NULL,
  `reading_date` date NOT NULL,
  `page_start` smallint unsigned NOT NULL,
  `page_end` smallint unsigned NOT NULL,
  `surah_start` tinyint unsigned NOT NULL,
  `ayah_start` smallint unsigned NOT NULL,
  `surah_end` tinyint unsigned NOT NULL,
  `ayah_end` smallint unsigned NOT NULL,
  `mushaf_label` varchar(100) DEFAULT NULL,
  `notes` text,
  `source` varchar(20) NOT NULL DEFAULT 'manual',
  `submitted_by_type` varchar(20) NOT NULL,
  `submitted_by_id` bigint unsigned NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `verified_by` bigint unsigned DEFAULT NULL,
  `verified_at` timestamp NULL DEFAULT NULL,
  `verification_notes` text,
  `sheet_id` bigint unsigned DEFAULT NULL,
  `sheet_row_number` tinyint unsigned DEFAULT NULL,
  `scan_id` bigint unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `quran_sheet_row_unique` (`sheet_id`,`sheet_row_number`),
  KEY `quran_reading_entries_reading_date_index` (`reading_date`),
  KEY `quran_reading_entries_status_index` (`status`),
  KEY `quran_reading_entries_siswa_status_reading_date_index` (`siswa_id`,`status`,`reading_date`),
  KEY `quran_reading_entries_submitted_by_type_submitted_by_id_index` (`submitted_by_type`,`submitted_by_id`),
  KEY `quran_reading_entries_verified_by_foreign` (`verified_by`),
  KEY `quran_reading_entries_scan_id_foreign` (`scan_id`),
  CONSTRAINT `quran_reading_entries_siswa_id_foreign` FOREIGN KEY (`siswa_id`) REFERENCES `siswa` (`id`) ON DELETE CASCADE,
  CONSTRAINT `quran_reading_entries_verified_by_foreign` FOREIGN KEY (`verified_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `quran_reading_entries_sheet_id_foreign` FOREIGN KEY (`sheet_id`) REFERENCES `quran_reading_sheets` (`id`) ON DELETE SET NULL,
  CONSTRAINT `quran_reading_entries_scan_id_foreign` FOREIGN KEY (`scan_id`) REFERENCES `quran_reading_scans` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
