<!DOCTYPE html>
<html lang="id"><head><meta charset="UTF-8"><title>Lembar Bacaan Al-Qur'an Mingguan</title><style>
@page{margin:10mm}body{font-family:DejaVu Sans,sans-serif;color:#111827;font-size:9px;margin:0}.page{position:relative;min-height:271mm;page-break-after:always}.page:last-child{page-break-after:auto}.corner{position:absolute;width:22px;height:22px;border-color:#111;border-style:solid}.tl{top:0;left:0;border-width:5px 0 0 5px}.tr{top:0;right:0;border-width:5px 5px 0 0}.bl{bottom:0;left:0;border-width:0 0 5px 5px}.br{bottom:0;right:0;border-width:0 5px 5px 0}.head{width:100%;border-bottom:2.5px solid #087f5b;padding-bottom:7px}.head td{vertical-align:middle}.qr-wrap{width:42mm;height:42mm;padding:3mm;background:#fff;box-sizing:border-box}.qr{display:block;width:36mm;height:36mm}.title{font-size:16px;font-weight:bold}.info{width:100%;margin:7px 0;border-collapse:collapse}.info td{padding:2px 6px 2px 0}.rows{width:100%;border-collapse:collapse;table-layout:fixed}.rows th,.rows td{border:1.8px solid #1f2937;padding:5px 3px;height:58px}.rows th{height:32px;background:#e9f7f1;font-size:8px}.note{margin-top:7px;color:#4b5563;font-size:8px}.token{font-family:monospace;font-size:7px;color:#6b7280}
</style></head><body>
@foreach($pages as $page)
@php($sheet = $page['sheet']) @php($siswa = $page['siswa'])
<section class="page"><span class="corner tl"></span><span class="corner tr"></span><span class="corner bl"></span><span class="corner br"></span>
<table class="head"><tr><td><div class="title">Lembar Bacaan Al-Qur'an Mingguan</div><div>PKG Desa Panunggangan &middot; Satu baris untuk satu hari &middot; Gunakan tinta gelap</div></td><td width="160"><div class="qr-wrap"><img class="qr" src="{{ $page['qrDataUri'] }}" alt="QR lembar"></div></td></tr></table>
@php($maskedNis = str_repeat('*', max(0, strlen((string)$siswa->nis)-4)).substr((string)$siswa->nis, -4))
@php($last = $sheet->last_position)
<table class="info"><tr><td width="16%"><strong>Nama Generus</strong></td><td>{{ $siswa->nama }} &middot; NIS {{ $maskedNis }}</td><td width="18%"><strong>Kelas/Kelompok</strong></td><td>{{ $siswa->kelas?->nama ?? '-' }} / {{ $siswa->kelompok_label ?? $siswa->kelompok ?? '-' }}</td></tr><tr><td><strong>Posisi terakhir</strong></td><td colspan="3">@if($last){{ $last['page_end'] ? 'Halaman '.$last['page_end'].' · ' : 'Halaman tidak dicatat · ' }}{{ $catalog::name((int)$last['surah_end']) }} ayat {{ $last['ayah_end'] }} &middot; {{ $last['reading_date'] }}@else Belum ada bacaan terverifikasi @endif</td></tr></table>
<table class="rows"><thead><tr><th style="width:4%">No.</th><th style="width:11%">Tanggal</th><th style="width:8%">Hal. awal</th><th style="width:8%">Hal. akhir</th><th style="width:10%">No. surat awal</th><th style="width:9%">Ayat awal</th><th style="width:10%">No. surat akhir</th><th style="width:9%">Ayat akhir</th><th>Catatan/Paraf</th></tr></thead><tbody>@for($i=1;$i<=$sheet->row_count;$i++)<tr><td style="text-align:center;font-weight:bold">{{ $i }}</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>@endfor</tbody></table>
<div class="note"><strong>Cara mengisi:</strong> tanggal DD/MM/YYYY; nomor surat 1&ndash;114; tulis satu rangkaian bacaan per baris. Periksa kembali hasil scan sebelum menyimpan.</div><div class="token">ID lembar: {{ $sheet->public_id }} &middot; Template v{{ $sheet->template_version ?? 1 }} &middot; Dibuat {{ $sheet->created_at->format('d/m/Y H:i') }} WIB</div>
</section>
@endforeach
</body></html>
