<!DOCTYPE html>
<html lang="id"><head><meta charset="UTF-8"><title>Riwayat Bacaan Al-Qur'an</title><style>
    @page{margin:18mm 14mm}body{font-family:DejaVu Sans,sans-serif;color:#172033;font-size:10px}h1{font-size:18px;margin:0 0 4px}.muted{color:#586174}.header{border-bottom:2px solid #087f5b;padding-bottom:10px;margin-bottom:14px}.identity{width:100%;border-collapse:collapse;margin-bottom:14px}.identity td{padding:3px 8px 3px 0}.entries{width:100%;border-collapse:collapse}.entries th,.entries td{border:1px solid #aeb7c4;padding:6px 5px;vertical-align:top}.entries th{background:#e9f7f1;text-align:left}.footer{margin-top:14px;font-size:8px;color:#6b7280}.status{font-weight:bold;color:#087f5b}
</style></head><body>
<div class="header"><h1>Riwayat Bacaan Al-Qur'an</h1><div class="muted">PKG Desa Panunggangan · Hanya catatan terverifikasi</div></div>
<table class="identity"><tr><td width="20%"><strong>Nama</strong></td><td>{{ $siswa->nama }}</td><td width="18%"><strong>NIS</strong></td><td>{{ $siswa->nis }}</td></tr><tr><td><strong>Kelas Sekolah</strong></td><td>{{ $siswa->school_grade_label }}</td><td><strong>Kelompok</strong></td><td>{{ $siswa->kelompok_label ?? $siswa->kelompok ?? '-' }}</td></tr><tr><td><strong>Pamong Binaan</strong></td><td>{{ $pamongNames }}</td><td><strong>Level PKG Efektif</strong></td><td>{{ $siswa->target_grade_label }}</td></tr><tr><td><strong>Periode</strong></td><td colspan="3">{{ $filters['start_date'] ?? 'Awal data' }} sampai {{ $filters['end_date'] ?? now()->toDateString() }}</td></tr></table>
<table class="entries"><thead><tr><th width="4%">No.</th><th width="13%">Tanggal</th><th width="12%">Halaman</th><th width="25%">Dari</th><th width="25%">Sampai</th><th>Catatan</th></tr></thead><tbody>
@forelse($entries as $entry)<tr><td>{{ $loop->iteration }}</td><td>{{ $entry->reading_date->format('d/m/Y') }}</td><td>@if($entry->page_count){{ $entry->page_start }}–{{ $entry->page_end }}<br><span class="muted">{{ $entry->page_count }} hal.</span>@else<span class="muted">Halaman tidak dicatat</span>@endif</td><td>{{ $catalog::name($entry->surah_start) }}<br>Ayat {{ $entry->ayah_start }}</td><td>{{ $catalog::name($entry->surah_end) }}<br>Ayat {{ $entry->ayah_end }}</td><td>{{ $entry->notes ?: '-' }}<br><span class="status">Terverifikasi</span></td></tr>@empty<tr><td colspan="6" style="text-align:center;padding:18px">Belum ada catatan terverifikasi pada periode ini.</td></tr>@endforelse
</tbody></table><div class="footer">Dokumen dibuat otomatis pada {{ now()->format('d/m/Y H:i') }} WIB. Keaslian data bersumber dari sistem PKG.</div>
</body></html>
