<!DOCTYPE html>
<html lang="id"><head><meta charset="UTF-8"><title>Lembar Lanjutan Bacaan Al-Qur'an</title><style>
    @page{margin:10mm}body{font-family:DejaVu Sans,sans-serif;color:#111827;font-size:9px}.corner{position:fixed;width:14px;height:14px;border-color:#111;border-style:solid}.tl{top:0;left:0;border-width:3px 0 0 3px}.tr{top:0;right:0;border-width:3px 3px 0 0}.bl{bottom:0;left:0;border-width:0 0 3px 3px}.br{bottom:0;right:0;border-width:0 3px 3px 0}.head{width:100%;border-bottom:2px solid #087f5b;padding-bottom:7px}.head td{vertical-align:middle}.qr{width:76px;height:76px}.title{font-size:16px;font-weight:bold}.info{width:100%;margin:7px 0;border-collapse:collapse}.info td{padding:2px 6px 2px 0}.rows{width:100%;border-collapse:collapse;table-layout:fixed}.rows th,.rows td{border:1px solid #4b5563;padding:4px 3px;height:24px}.rows th{background:#e9f7f1;font-size:8px}.note{margin-top:7px;color:#4b5563;font-size:8px}.token{font-family:monospace;font-size:7px;color:#6b7280}
</style></head><body><span class="corner tl"></span><span class="corner tr"></span><span class="corner bl"></span><span class="corner br"></span>
<table class="head"><tr><td><div class="title">Lembar Lanjutan Bacaan Al-Qur'an</div><div>PKG Desa Panunggangan · Isi angka dengan jelas menggunakan tinta gelap</div></td><td width="82"><img class="qr" src="{{ $qrDataUri }}" alt="QR lembar"></td></tr></table>
@php
    $maskedNis = str_repeat('*', max(0, strlen((string)$siswa->nis)-4)).substr((string)$siswa->nis, -4);
    $last = $sheet->last_position;
@endphp
<table class="info"><tr><td width="16%"><strong>Nama Generus</strong></td><td>{{ $siswa->nama }} · NIS {{ $maskedNis }}</td><td width="18%"><strong>Kelas/Kelompok</strong></td><td>{{ $siswa->kelas?->nama ?? '-' }} / {{ $siswa->kelompok_label ?? $siswa->kelompok ?? '-' }}</td></tr><tr><td><strong>Posisi terakhir</strong></td><td colspan="3">@if($last)Halaman {{ $last['page_end'] }} · {{ $catalog::name((int)$last['surah_end']) }} ayat {{ $last['ayah_end'] }} · {{ $last['reading_date'] }}@else Belum ada bacaan terverifikasi @endif</td></tr></table>
<table class="rows"><thead><tr><th style="width:4%">No.</th><th style="width:11%">Tanggal</th><th style="width:8%">Hal. awal</th><th style="width:8%">Hal. akhir</th><th style="width:10%">No. surat awal</th><th style="width:9%">Ayat awal</th><th style="width:10%">No. surat akhir</th><th style="width:9%">Ayat akhir</th><th>Catatan/Paraf</th></tr></thead><tbody>@for($i=1;$i<=$sheet->row_count;$i++)<tr><td style="text-align:center;font-weight:bold">{{ $i }}</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>@endfor</tbody></table>
<div class="note"><strong>Cara mengisi:</strong> tanggal DD/MM/YYYY; nomor surat 1–114; tulis satu rangkaian bacaan per baris. Setelah terisi, {{ config('quran-reading.scan_enabled') ? 'buka menu Scan Lembar Bacaan dan periksa kembali semua hasil sebelum disimpan' : 'simpan lembar ini untuk pencatatan lanjutan; pemindaian akan tersedia setelah tahap pilot selesai' }}.</div><div class="token">ID lembar: {{ $sheet->public_id }} · Dibuat {{ $sheet->created_at->format('d/m/Y H:i') }} WIB</div>
</body></html>
